[project]
name = "puch-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.8.1",
    "markdownify>=1.1.0",
    "openai>=1.88.0",
    "pypdf2>=3.0.1",
    "readabilipy>=0.3.0",
]
